Wiki Famous People -*- mode: org -*-

* Wikipedia /Semi/ famous person downloader

** Get a set of random people from *Wikidata* that meet the following criteria:
        1. Born on the year provided by rand()
        2. Has a pic on file
        3. Is not a sports figure
        4. The associated wiki article has a minimum of 20 inbound inter-wiki site links

** After getting the list from *Wikidata* it will then use the *Wikipedia* API to get the text version of the article. For the blurb only the first 2 sentences are retained. Dump this into a txt file with the corresponding name.

** After that, it will request a specific size image from Wikipedia so that we don't get huge pictures and we have a set column with for later.

** Using Image Magick, convert the pictures in SIXEL format for the terminal.

        - Image Magick :: because I might want to add a border or post processing later

** The idea for this Frankenstein python script came from the fact that I wanted something like neofetch for interesting Wikipedia people. That way when ever I open my terminal I have a new interesting person to learn about.
